// match service model, those props generated by service are optional on frontend
export interface User {
    _id?: string; // <- generated by service
    displayName?: string;
    firstName: string;
    lastName: string;
};
